### ISSUE TITLE
[Plugin Compatibility Bug] 3D Item's armor stand visible

### ISSUE THREAD

**Issue by joex92** [LOOHP/InteractionVisualizer#71]
There's this plugin called [3D Items](https://www.spigotmc.org/resources/3ditems.88479/) that shows the items as 3D items when dropped, as far as I know what the plugin does is to send to the client an invisible armor stand with the item making it look like the item is in 3D...
The issue with InteractionVisualizer is that that invisible armor stand is visible, idk why, but when both plugins are enabled, the 3D Item's armor stand is visible... [here's the explanation the 3D item's dev gave me about this](https://www.spigotmc.org/threads/3ditems.486881/page-3#post-4275278), Idk if there's an option as a workaround... I even tried disabling the item feature from InteractionVisualizer, but it didn't work...

**Comment by LOOHP** [comment]
I've just looked into this issue. The plugin conflict lies in the item display module in InteractionVisualizer. (If you disable Entities.Items in InteractionVisualizer this problem disappears.)
The reason the conflict exists is due to how 3D Items spawn armorstands and how InteractionVisualizer modifies the metadata of the dropped items. 3D Items first despawn the item client side and then use the same entity id to spawn a client side armorstand to create a 3D item. However, the server nor other plugins know this, so InteractionVisualizer sends its own metadata packet (containing the metadata of the item and its custom display name) thinking it is still a dropped item client side.

**Comment by joex92** [comment]
oohh ok ok... I understand now... so then the only way is to disable the `Entities.Items` feature...

Do you believe there is a workaround so `Entities.items` is not disabled? (just wondering, not asking for you to do it)

**Comment by LOOHP** [comment]
Maybe 3DItems can set the original item entity to be invisible server side to let other plugins know?

**Comment by joex92** [comment]
hmm... could be a solution... 
anyways, I just did what you told me to disable `Entities.Items`, it worked, thanks...
So I'll close it for now...
